ktor:
  application:
    modules:
      - ru.clevertec.ApplicationKt.module
  deployment:
    port: 8090
database:
  url: jdbc:postgresql://localhost:5434/tracking-api
  user: admin
  password: pass
  driver: org.postgresql.Driver
  maxPoolSize: 10
liquibase:
  changelog: db/changelog/db.changelog-master.yaml

kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    groupId: "book-service-consumer-group"
    clientId: "book-service-consumer"
    autoOffsetReset: "earliest"
    enableAutoCommit: false
  topics:
    bookEvents: "book-events"
    authorEvents: "author-events"
jwt:
  issuer: "library-service"
  secret: "your-secret-key-change-in-production"